CREATE DATABASE CigarShop

CREATE TABLE Sizes
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Length] INT NOT NULL, 
		CONSTRAINT [Length] CHECK ([Length] BETWEEN 10 AND 25),
	RingRange DECIMAL(10, 2) NOT NULL, 
		CONSTRAINT RingRange CHECK (RingRange BETWEEN 1.5 AND 7.5)
)

CREATE TABLE Tastes
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	TasteType VARCHAR(20) NOT NULL,
	TasteStrength VARCHAR(15) NOT NULL,
	ImageURL NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Brands
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	BrandName NVARCHAR(30) UNIQUE NOT NULL,
	BrandDescription NVARCHAR(MAX)
)

CREATE TABLE Cigars
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	CigarName NVARCHAR(80) NOT NULL,
	BrandId INT FOREIGN KEY REFERENCES Brands(Id) NOT NULL,
	TastId INT FOREIGN KEY REFERENCES Tastes(Id) NOT NULL,
	SizeId INT FOREIGN KEY REFERENCES Sizes(Id) NOT NULL,
	PriceForSingleCigar DECIMAL(10, 2) NOT NULL,
	ImageURL NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Addresses
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Town VARCHAR(30) NOT NULL,
	Country NVARCHAR(30) NOT NULL,
	Streat NVARCHAR(100) NOT NULL,
	ZIP VARCHAR(20) NOT NULL
)

CREATE TABLE Clients
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL
)

CREATE TABLE ClientsCigars
(
	ClientId INT FOREIGN KEY REFERENCES Clients(Id) NOT NULL,
	CigarId INT FOREIGN KEY REFERENCES Cigars(Id) NOT NULL
	PRIMARY KEY(ClientId, CigarId)
)